export type Cdi = {
    id: number,
    locationabbr: string,
    locationname: string,
    topic: string,
    yearstart: number,
    yearend: number,
    question: string,
    datavalueunit: string,
    datavaluetype: string,
    datavalue: string,
    topicid: string,
    questionid: string,
    datavaluetypeid: string,
    gender: string,
    genderid: string,
    race: string,
    raceid: string,
}